### ISSUE TITLE
[FEATURE REQUEST] Allow selection of a specific light segment in a ledstrip

### ISSUE THREAD

**Issue by JustJoostNL** [Joery-M/Govee-LAN-Control#3]
Would it be possible to only set the color of a specific light segment in the strip, that way, you can create cool effects? This is already possible in the Govee app for mobile.

**Comment by Joery-M** [comment]
I would love to add this, but Govee currently doesn't give any commands for this. If it ever does get added, I'll will for sure support it (since I would want it too)
